import {
	MESH_SCHEMA,
	parseCheckpointManifest,
	sha256CanonicalJson,
	toImmutableJson,
	type CheckpointManifestV1,
	type JsonRecord,
	type JsonValue,
} from "@pk-nerdsaver-ai/mesh-contracts";

export type CreateCheckpointManifestInput = Omit<CheckpointManifestV1, "schemaVersion" | "contentDigest" | "manifestDigest">;

/** A checkpoint is metadata and artifact references only; it must never embed file bytes. */
export class CheckpointSafetyError extends Error {
	readonly path: string;

	constructor(path: string, message: string) {
		super(`${path}: ${message}`);
		this.name = "CheckpointSafetyError";
		this.path = path;
	}
}

const FORBIDDEN_FILE_FIELDS = new Set(["content", "contents", "data", "bytes", "text", "binary", "patch", "diff"]);
const SECRET_KEY = /secret|password|token|credential|authorization|private.?key|api.?key/i;
const SECRET_VALUE = [
	/-----BEGIN(?: [A-Z]+)? PRIVATE KEY-----/i,
	/\b(?:ghp|github_pat|sk|nsec)_[A-Za-z0-9_-]{8,}/,
	/\/\/[^/\s:@]+:[^/\s@]+@/,
] as const;

function fail(path: string, message: string): never {
	throw new CheckpointSafetyError(path, message);
}

function asRecord(value: JsonValue, path: string): JsonRecord {
	if (value === null || Array.isArray(value) || typeof value !== "object") fail(path, "must be an object");
	return value;
}

function assertNoSecretMaterial(value: JsonValue, path: string): void {
	if (typeof value === "string") {
		if (SECRET_VALUE.some(pattern => pattern.test(value))) fail(path, "must not contain credential material");
		return;
	}
	if (value === null || typeof value === "number" || typeof value === "boolean") return;
	if (Array.isArray(value)) {
		for (const [index, entry] of value.entries()) assertNoSecretMaterial(entry, `${path}[${index}]`);
		return;
	}
	for (const [key, entry] of Object.entries(value)) {
		if (SECRET_KEY.test(key) && key !== "secretScan") fail(`${path}.${key}`, "must not contain credential-bearing fields");
		assertNoSecretMaterial(entry, `${path}.${key}`);
	}
}

function assertMetadataEntries(value: JsonValue | undefined, path: string): void {
	if (!Array.isArray(value)) fail(path, "must be an array of metadata records");
	for (const [index, entry] of value.entries()) {
		const record = asRecord(entry, `${path}[${index}]`);
		for (const key of Object.keys(record)) {
			if (FORBIDDEN_FILE_FIELDS.has(key.toLowerCase())) {
				fail(`${path}[${index}].${key}`, "must not embed workspace file content");
			}
		}
		if (typeof record.path !== "string" || record.path.length === 0) fail(`${path}[${index}].path`, "must be a path");
	}
}

function omitDigests(record: JsonRecord): JsonRecord {
	const result: Record<string, JsonValue> = {};
	for (const [key, value] of Object.entries(record)) {
		if (key !== "contentDigest" && key !== "manifestDigest") result[key] = value;
	}
	return result;
}

function checkpointContentDigest(record: JsonRecord): string {
	return sha256CanonicalJson(omitDigests(record));
}

function assertCheckpointSafety(record: JsonRecord): void {
	assertNoSecretMaterial(record, "$");
	assertMetadataEntries(record.files, "$.files");
	assertMetadataEntries(record.excluded, "$.excluded");
}

/** Build a self-verifying checkpoint manifest without ever accepting raw workspace files. */
export function createCheckpointManifest(input: CreateCheckpointManifestInput): CheckpointManifestV1 {
	const immutableInput = asRecord(toImmutableJson(input), "$");
	const base: Record<string, JsonValue> = {};
	for (const [key, value] of Object.entries(immutableInput)) {
		if (key === "schemaVersion" || key === "contentDigest" || key === "manifestDigest") {
			fail(`$.${key}`, "is generated by the checkpoint builder");
		}
		base[key] = value;
	}
	base.schemaVersion = MESH_SCHEMA.checkpoint;
	assertCheckpointSafety(base);
	base.contentDigest = checkpointContentDigest(base);
	base.manifestDigest = sha256CanonicalJson(base);
	return validateCheckpointManifest(base);
}

/** Validate the mesh contract, derived content digest, and strict metadata-only safety boundary. */
export function validateCheckpointManifest(input: unknown): CheckpointManifestV1 {
	const manifest = parseCheckpointManifest(input);
	const record = asRecord(toImmutableJson(manifest), "$");
	assertCheckpointSafety(record);
	if (manifest.contentDigest !== checkpointContentDigest(record)) {
		fail("$.contentDigest", "does not match the checkpoint metadata digest");
	}
	return manifest;
}
