import { Buffer } from "node:buffer";
import { loadNative } from "./loader-state.js";

/**
 * Native addon entrypoint.
 *
 * Hand-written surface area: one `loadNative()` call. Everything else in
 * this file (the surface-area `export const` block between MARKER_START
 * and MARKER_END) is rewritten by `packages/natives/scripts/gen-enums.ts`
 * after `napi build` regenerates `index.d.ts`.
 *
 * Loader logic lives in `./loader-state.js` so the pure helpers stay
 * unit-testable without triggering AVX2 detection or filesystem probes on
 * import. Types are auto-generated by napi-rs in `./index.d.ts`.
 */

const loadedBindings = loadNative();

/**
 * JS-side ceiling for in-memory `astMatch` sources, in bytes. Mirrors
 * `MAX_AST_SOURCE_BYTES` in `crates/pi-natives/src/ast.rs` (2 MiB), which is
 * the authoritative ceiling enforced natively. This value MUST stay <= the
 * Rust constant so oversized sources are rejected here — before the string
 * crosses into native and before parser/tree construction — while the native
 * check remains the last line of defense for callers that bypass this module.
 */
export const MAX_AST_SOURCE_BYTES = 2 * 1024 * 1024;

const nativeAstMatch = loadedBindings.astMatch;

/**
 * `astMatch` with a JS-side source-size guard. Rejects oversized sources with
 * the same message the native layer produces, so callers get one contract
 * regardless of which side of the boundary rejects the input.
 */
async function guardedAstMatch(options) {
	const source = options?.source;
	if (typeof source === "string" && Buffer.byteLength(source, "utf8") > MAX_AST_SOURCE_BYTES) {
		throw new Error(`ast match source exceeds the ${MAX_AST_SOURCE_BYTES / (1024 * 1024)} MiB AST safety limit`);
	}
	return nativeAstMatch(options);
}

// Shadow the raw binding on a fresh object so the generated export block below
// picks up the guarded `astMatch` without mutating the shared addon exports.
const nativeBindings = { ...loadedBindings, astMatch: guardedAstMatch };
// --- generated native exports (do not edit) ---
// classes
export const MacAppearanceObserver = nativeBindings.MacAppearanceObserver;
export const MacOSPowerAssertion = nativeBindings.MacOSPowerAssertion;
export const Process = nativeBindings.Process;
export const PtySession = nativeBindings.PtySession;
export const Shell = nativeBindings.Shell;

// functions
export const __ompInstallTokioRuntime = nativeBindings.__ompInstallTokioRuntime;
export const __piNativesV16_4_26 = nativeBindings.__piNativesV16_4_26;
export const applyBashFixups = nativeBindings.applyBashFixups;
export const astEdit = nativeBindings.astEdit;
export const astGrep = nativeBindings.astGrep;
export const astMatch = nativeBindings.astMatch;
export const blockRangeAt = nativeBindings.blockRangeAt;
export const copyToClipboard = nativeBindings.copyToClipboard;
export const countTokens = nativeBindings.countTokens;
export const detectMacOSAppearance = nativeBindings.detectMacOSAppearance;
export const enclosingBlockBoundaries = nativeBindings.enclosingBlockBoundaries;
export const encodeSixel = nativeBindings.encodeSixel;
export const executeShell = nativeBindings.executeShell;
export const extractSegments = nativeBindings.extractSegments;
export const fuzzyFind = nativeBindings.fuzzyFind;
export const getSupportedLanguages = nativeBindings.getSupportedLanguages;
export const getWorkProfile = nativeBindings.getWorkProfile;
export const glob = nativeBindings.glob;
export const grep = nativeBindings.grep;
export const hasMatch = nativeBindings.hasMatch;
export const highlightCode = nativeBindings.highlightCode;
export const htmlToMarkdown = nativeBindings.htmlToMarkdown;
export const invalidateFsScanCache = nativeBindings.invalidateFsScanCache;
export const isoBackend = nativeBindings.isoBackend;
export const isoDiff = nativeBindings.isoDiff;
export const isoIsUnavailableError = nativeBindings.isoIsUnavailableError;
export const isoProbe = nativeBindings.isoProbe;
export const isoResolve = nativeBindings.isoResolve;
export const isoStart = nativeBindings.isoStart;
export const isoStop = nativeBindings.isoStop;
export const listWorkspace = nativeBindings.listWorkspace;
export const matchesKey = nativeBindings.matchesKey;
export const matchesKittySequence = nativeBindings.matchesKittySequence;
export const matchesLegacySequence = nativeBindings.matchesLegacySequence;
export const parseKey = nativeBindings.parseKey;
export const parseKittySequence = nativeBindings.parseKittySequence;
export const readImageFromClipboard = nativeBindings.readImageFromClipboard;
export const renderSnapcompactPng = nativeBindings.renderSnapcompactPng;
export const search = nativeBindings.search;
export const setHangulCompatJamoWidthOverride = nativeBindings.setHangulCompatJamoWidthOverride;
export const sliceWithWidth = nativeBindings.sliceWithWidth;
export const summarizeCode = nativeBindings.summarizeCode;
export const supportsLanguage = nativeBindings.supportsLanguage;
export const truncateToWidth = nativeBindings.truncateToWidth;
export const visibleWidth = nativeBindings.visibleWidth;
export const wrapTextWithAnsi = nativeBindings.wrapTextWithAnsi;

// string/numeric enums (napi-rs string_enum produces TS-only const enum)
export const AstMatchStrictness = {
	Cst: "cst",
	Smart: "smart",
	Ast: "ast",
	Relaxed: "relaxed",
	Signature: "signature",
	Template: "template",
};
export const Ellipsis = {
	Unicode: 0,
	Ascii: 1,
	Omit: 2,
};
export const Encoding = {
	O200kBase: "O200kBase",
	Cl100kBase: "Cl100kBase",
};
export const FileType = {
	File: 1,
	Dir: 2,
	Symlink: 3,
};
export const GrepOutputMode = {
	Content: "content",
	Count: "count",
	FilesWithMatches: "filesWithMatches",
};
export const IsoBackendKind = {
	Apfs: 0,
	Btrfs: 1,
	Zfs: 2,
	LinuxReflink: 3,
	Overlayfs: 4,
	WindowsBlockClone: 5,
	Projfs: 6,
	Rcopy: 7,
};
export const IsoChangeKind = {
	Added: 0,
	Modified: 1,
	Removed: 2,
};
export const KeyEventType = {
	Press: 1,
	Repeat: 2,
	Release: 3,
};
export const MacOSAppearance = {
	Dark: "dark",
	Light: "light",
};
export const ProcessStatus = {
	Running: "running",
	Exited: "exited",
};
// --- end generated native exports ---
