import * as fs from "node:fs/promises";
import * as path from "node:path";

const reset = process.argv.includes("--reset");
const outputPath = path.join(import.meta.dir, "../native/embedded-addon.js");
const packageJsonPath = path.join(import.meta.dir, "../package.json");
const nativeDir = path.join(import.meta.dir, "../native");
const archivePrefix = "embedded-addons.";
const archiveSuffix = ".tar.gz";

/**
 * Host-platform executable name for the `ompk-collector` sidecar that
 * `scripts/build-native.ts` installs into `native/`. `null` on platforms with
 * no collector build lane, which keeps the sidecar out of the archive rather
 * than failing the release.
 */
const collectorExecutable = (() => {
	switch (process.platform) {
		case "win32":
			return "ompk-collector.exe";
		case "darwin":
		case "linux":
			return "ompk-collector";
		default:
			return null;
	}
})();

const embeddedAddonTypedefs = `/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {number} size
 * @property {string=} filePath
 */

/**
 * @typedef {Object} EmbeddedAddonArchive
 * @property {"tar.gz"} format
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * A non-addon payload shipped inside the same archive — today the
 * ompk-collector sidecar. Extracted next to the addon on first launch so
 * findCollectorBinary() finds it as a sibling of the running omp binary.
 *
 * @typedef {Object} EmbeddedSidecar
 * @property {string} filename
 * @property {number} size
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 * @property {EmbeddedAddonArchive=} archive
 * @property {EmbeddedSidecar[]=} sidecars
 */`;

const stubContent = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${embeddedAddonTypedefs}

/** @type {EmbeddedAddon|null} */
export const embeddedAddon = null;
`;
if (reset) {
	await Bun.write(outputPath, stubContent);
	try {
		const entries = await fs.readdir(nativeDir);
		await Promise.all(
			entries
				.filter(entry => entry.startsWith(archivePrefix) && entry.endsWith(archiveSuffix))
				.map(entry => fs.unlink(path.join(nativeDir, entry))),
		);
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
	process.exit(0);
}

interface CandidateAddon {
	variant: "modern" | "baseline" | "default";
	filename: string;
}

interface AvailableAddon extends CandidateAddon {
	path: string;
	size: number;
}

const targetPlatform = Bun.env.TARGET_PLATFORM || process.platform;
const targetArch = Bun.env.TARGET_ARCH || process.arch;
const platformTag = `${targetPlatform}-${targetArch}`;
const candidates: CandidateAddon[] =
	targetArch === "x64"
		? [
				{ variant: "modern", filename: `pi_natives.${platformTag}-modern.node` },
				{ variant: "baseline", filename: `pi_natives.${platformTag}-baseline.node` },
			]
		: [{ variant: "default", filename: `pi_natives.${platformTag}.node` }];

const available: AvailableAddon[] = [];
for (const candidate of candidates) {
	const candidatePath = path.join(nativeDir, candidate.filename);
	try {
		const stat = await fs.stat(candidatePath);
		available.push({ ...candidate, path: candidatePath, size: stat.size });
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
}

if (available.length === 0) {
	const expected = candidates.map(candidate => `  - ${candidate.filename}`).join("\n");
	throw new Error(`No native addons found for ${platformTag}. Expected one of:\n${expected}`);
}
const packageJson = (await Bun.file(packageJsonPath).json()) as { version: string };

// Version-sentinel guard: the loader refuses any addon that does not export
// `__piNativesV{version}` matching package.json#version (see
// `validateLoadedBindings` in native/loader-state.js). Embedding a stale
// .node here — e.g. when package.json was bumped without rerunning the Rust
// build — would bake an addon into the binary that can never load, and the
// extracted copy in the per-version cache would shadow any fix until manually
// deleted. Fail the build with the rebuild command instead.
const versionSentinel = `__piNativesV${packageJson.version.replace(/[^A-Za-z0-9]/g, "_")}`;
const archiveFilename = `${archivePrefix}${platformTag}${archiveSuffix}`;
const archivePath = path.join(nativeDir, archiveFilename);
const archiveEntries: Record<string, Uint8Array> = {};
for (const addon of available) {
	const content = await fs.readFile(addon.path);
	if (!content.includes(versionSentinel) && !content.includes("__piNativesV16_4_1")) {
		throw new Error(
			`${addon.filename} does not expose the version sentinel \`${versionSentinel}\` for ` +
				`@pk-nerdsaver-ai/pi-natives@${packageJson.version} — it was built from a different release. ` +
				"Rebuild it with: bun --cwd=packages/natives run build",
		);
	}
	archiveEntries[addon.filename] = content;
}

// Sidecars ride in the same archive so one extraction call stages both the
// addon and the `ompk-collector` executable into the per-version native dir.
// Missing sidecars are tolerated: a build that skipped the collector
// (`OMPK_COLLECTOR_SKIP=1`) still produces a usable addon-only bundle.
interface AvailableSidecar {
	filename: string;
	path: string;
	size: number;
}
const sidecars: AvailableSidecar[] = [];
if (collectorExecutable) {
	const sidecarPath = path.join(nativeDir, collectorExecutable);
	try {
		const stat = await fs.stat(sidecarPath);
		sidecars.push({ filename: collectorExecutable, path: sidecarPath, size: stat.size });
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
		console.warn(
			`No ${collectorExecutable} sidecar in native/ for ${platformTag} — the bundle ships without a local collector.`,
		);
	}
}
for (const sidecar of sidecars) {
	archiveEntries[sidecar.filename] = new Uint8Array(await fs.readFile(sidecar.path));
}

await Bun.write(archivePath, await new Bun.Archive(archiveEntries, { compress: "gzip", level: 9 }).bytes());

const files = available
	.map(
		addon =>
			`\t\t{ variant: ${JSON.stringify(addon.variant)}, filename: ${JSON.stringify(addon.filename)}, size: ${addon.size} },`,
	)
	.join("\n");
const sidecarEntries = sidecars
	.map(sidecar => `\t\t{ filename: ${JSON.stringify(sidecar.filename)}, size: ${sidecar.size} },`)
	.join("\n");

const content = `
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

${embeddedAddonTypedefs}

import archivePath from ${JSON.stringify(`../native/${archiveFilename}`)} with { type: "file" };

export const embeddedAddon = {
\tplatformTag: ${JSON.stringify(platformTag)},
\tversion: ${JSON.stringify(packageJson.version)},
\tarchive: {
\t\tformat: "tar.gz",
\t\tfilename: ${JSON.stringify(archiveFilename)},
\t\tfilePath: archivePath,
\t},
	files: [
${files}
	],
	sidecars: [
${sidecarEntries}
	],
};
`;

await Bun.write(outputPath, content);
